import "./globals.css";
import { ReactLenis } from "lenis/react";
import { Kanit } from "next/font/google";
import '@fortawesome/fontawesome-free/css/all.min.css'

export const metadata = {
    title: "My Portfolio",
    description: "Generated by create next app",
};


const kanit = Kanit({
    variable: "--font-Kanit",
    subsets: ["latin"],
    weight: "300",
});


export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ReactLenis root>
                <body className={`${kanit.className}`}>{children}</body>
            </ReactLenis>
        </html>
    );
}
